### ISSUE TITLE
api: crashes during user registration

### ISSUE THREAD

**Issue by RossComputerGuy** [ExpidusOS/website#1]
```
server_api_1   | debug: receving request from http://172.21.04/v1/user/register (POST)
server_api_1   | Executing (default): SELECT `uuid`, `username`, `password`, `birthdate`, `email`, `createdAt`, `updatedAt` FROM `users` AS `User` WHERE `User`.`username` = 'TheComputerGuy';
db_1           | 2021-02-26  5:13:14 13 [Warning] Aborted connection 13 to db: 'expidus' user: 'expidus' host: '172.21.0.4' (Got an error reading communication packets)
server_api_1   | [nodemon] app crashed - waiting for file changes before starting...
```
Registering an account causes the API to crash. No solution exists so far.

**Comment by andersevenrud** [comment]
I'm unable to reproduce this issue. I had to change your salting to get this working (invalid number) as well as temporarily hard-code a UUID in the insert statement in order to be able to test this, but after that it works just fine:

```
server_api_1   | Executing (default): SELECT `uuid`, `username`, `password`, `birthdate`, `email`, `createdAt`, `updatedAt` FROM `users` AS `g` WHERE `g`.`username` = 'anders';
server_api_1   | Executing (default): INSERT INTO `users` (`uuid`,`username`,`password`,`birthdate`,`email`,`createdAt`,`updatedAt`) VALUES (?,?,?,?,?,?,?);
nginx_1        | 192.168.128.1 - - [27/Feb/2021:15:24:14 +0000] "POST /v1/user/register HTTP/1.1" 200 47 "-" "curl/7.74.0" "-"
```

```
[I] ➜ curl -XPOST https://api.expidusos.com/v1/user/register -H 'content-type: application/json' -H 'accept: application/json' -d '{"username":"anders", "password":"abc123", "birthdate":"2000", "email":"andersevenrud@gmail.com"}'
{"uuid":"dbb3b43d-ffc9-4eab-9bc5-db37e610152c"}%
```

**Comment by RossComputerGuy** [comment]
What's a valid number for the salt? And I thought the sequlize docs said that UUID's automatically generate.

**Comment by andersevenrud** [comment]
Number has to be divisible by 2. You can just keep the default number, an insanely high number that you provided does not really make it "more secure".

Also, don't use UUIDs as primary keys. These are best used in the public API for lookups etc. but **not** for the relational database.

There are several reasons I can think of on the top of my head:

* Not really sortable
* They consume more table space
* Makes it harder to debug
* **Very slow in table joins**

**Comment by andersevenrud** [comment]
And just a small note. You're storing the salt, not the hash on the user model:

https://github.com/ExpidusOS/website/blob/8bdac750166e3bac60c747dc1fad9b797e5088db/packages/api/src/models/user.ts#L52-L54

**Comment by RossComputerGuy** [comment]
https://github.com/ExpidusOS/website/commit/672e5fe20535f790b4f4e13e4c4091c504a32a83 Fixed the salt and setting the password

**Comment by andersevenrud** [comment]
As mentioned I got this in #2. This issue is actually due to the `INSERT` statement, not the `SELECT`. The `INSERT` just does not get printed in the log because of the abrupt disconnect.

**Comment by RossComputerGuy** [comment]
Interesting, is this a known sequlize issue?

**Comment by andersevenrud** [comment]
I figured it out. The `bcrypt` package was corrupt on my system [for unknown reasons]. It made the application exit silently!

Once manually removed and re-installed everything works as expected.

**Comment by andersevenrud** [comment]
Since bcrypt was used in the model when the query builder was active, this explains that weird error message. It crashed in the middle of a connection :)

**Comment by RossComputerGuy** [comment]
Alright, I'll do that on my desktop as well.

**Comment by andersevenrud** [comment]
Just remove the `node_modules/bcrypt` directory and restart the api service.
