### ISSUE TITLE
[RFC] Docker environment improvements

### ISSUE THREAD

**Issue by andersevenrud** [ExpidusOS/website#7]
There has been some discussion about this in PMs and #6 but the docker environment [in my opinion] needs some changes.

- [ ] Make sure everything defaults to a development environment
- [ ] Separate compose files for environments targeted for deployments
- [ ] I would recommend not using a domain on a development setup
- [ ] Make it possible to override the exposed service ports (80/443 directly on host is no good on a development setup)
    - [ ] Make default ports a high number to avoid host service collisions
- [ ] Github actions to produce docker images (to avioid checking out git repos on servers, etc.)
- [ ] Separate databases for applications in the repo, which implies maybe doing
    - [ ] Separate compose files for the applications
- [ ] User docker volumes

**Comment by RossComputerGuy** [comment]
>  I would recommend not using a domain on a development setup

Well, we'll need to figure out how to find the service's IP address for the wiki for development setups.

**Comment by andersevenrud** [comment]
> Well, we'll need to figure out how to find the service's IP address for the wiki for development setups.

One way to solve this is to use paths, not subdomains on the out-of-the box (development) setup.

https://github.com/ExpidusOS/website/blob/0e6225368b4dfd7273d40f49920a9ff7c3c117c2/data/wiki/LocalSettings.php#L33

Then this is set to ex  `http://localhost:port/wiki` via an env variable (I mention having the port customizable in the issue description) by default. Then on the production server this is just set to the actual hosting domain.

**Comment by RossComputerGuy** [comment]
Currently hosting via Docker on a single server.
