### ISSUE TITLE
Add ESLint

### ISSUE THREAD

**Issue by andersevenrud** [ExpidusOS/website#8]
Right now, the only way to get code diagnostics is via the TypeScript compiler. This is great and all, but it does not help you much while writing code.

Also, there's no rules on how to write the code and there are inconsistencies.

I recommend using ESLint and the "standard" rule set. This set does not use semicolons, which seems to be a love/hate things, but I'm all for it. Also, spaces, not tabs (a distant crowd shrieks).

**Comment by RossComputerGuy** [comment]
Definitely needs to be done, should test every push.

**Comment by andersevenrud** [comment]
Maybe even add git hooks for it so that it is checked before a commit.

**Comment by RossComputerGuy** [comment]
That would definitely be better.

**Comment by andersevenrud** [comment]
FYI: https://www.npmjs.com/package/git-hooks sets up git hooks for you when you install the application. Might be a good choice.

**Comment by RossComputerGuy** [comment]
So then would that mean we'd need a project-wide node project?

**Comment by andersevenrud** [comment]
Nope. The git-hooks hooks into the post install of npm, so it will "just work".

**Comment by andersevenrud** [comment]
Actually, good thing you mentioned that, because this can actually cause some unexpected behaviour when it comes to the `.git` folder. The docker context is not the same user as the host :thinking: 

So maybe a bootstrap script is better that just does this the "normal way".

**Comment by andersevenrud** [comment]
> So maybe a bootstrap script is better that just does this the "normal way".

This will make it so eslint runs on the host, and not inside the docker context. But this is pretty "safe" since eslint does not require any binaries, so it should run fine. It's not perfect, but works. Maybe make it a recommendation, but not mandatory. If the repo has Github Actions set up to catch this anyway, it would cover all cases except when someone goes committing directly into master without the stuff enabled, hehe.

But any of the main maintainers should have this set up anyways. PRs are covered via actions.

**Comment by RossComputerGuy** [comment]
Added when switched to Nuxt.JS
